config:
  # 1ターンが何秒か
  unitTime: 21600

  # 島の最大数
  maxIsland: 30
  
  # トップページに表示するログのターン数
  topLogTurn: 1
  
  # ログファイル保持ターン数
  logMax: 8
  
  # 発見ログ保持行数
  historyMax: 10
  
  # 放棄コマンド自動入力ターン数
  giveupTurn: 28
  
  # コマンド入力限界数
  commandMax: 20
  
  # ローカル掲示板行数を使用するかどうか(0:使用しない、1:使用する)
  useLbbs: 0
  
  # ローカル掲示板行数
  lbbsMax: 10
  
  # 島の大きさ
  # (変更できないかも)
  islandSize: 12
  
  # 他人から資金を見えなくするか
  # 0 見えない
  # 1 見える
  # 2 100の位で四捨五入
  hideMoneyMode: 2

  #----------------------------------------
  # 防衛施設の自爆
  #----------------------------------------
  # 怪獣に踏まれた時自爆するなら1、しないなら0
  dBaseAuto: 1

# 初期設定
default:
  # 初期資金
  initialMoney: 100

  # 初期食料
  initialFood: 100

  # 木の単位当たりの売値
  treeValue: 5

  # 名前変更のコスト
  costChangeName: 500

  # 人口1単位あたりの食料消費料
  eatenFood: 0.2

# 最大値
maxim:
  # 経験値の最大値
  expPoint: 200 # ただし、最大でも255まで

  # レベルの最大値
  # ミサイル基地
  baseLevel: 5
  # 海底基地
  sBaseLevel: 3 

  # 経験値がいくつでレベルアップか
  # ミサイル基地
  baseLevelUp: 
    - 20
    - 60
    - 120
    - 200 
  # 海底基地
  sBaseLevelUp:
    - 50
    - 200

const:
  landform: # 地形番号
    sea:      0  #海
    waste:    1  #荒地
    plains:   2  #平地
    town:     3  #町系
    forest:   4  #森
    farm:     5  #農場
    factory:  6  #工場
    base:     7  #ミサイル基地
    defence:  8  #防衛施設建設
    mountain: 9  #山
    monster:  10 #怪獣
    sbase:    11 #海底基地
    oil:      12 #海底油田
    monument: 13 #記念碑
    haribote: 14 #ハリボテ

monument:
  # 名前
  name: 
     - 'モノリス'
     - '平和記念碑'
     - '戦いの碑'

  # 画像ファイル
  image:
     - 'monument0.gif'
     - 'monument0.gif'
     - 'monument0.gif'

#----------------------------------------
# 災害
#----------------------------------------
disaster:
  # 通常災害発生率(確率は0.1%単位)
    earthquake: 5  # 地震
    tsunami:    15 # 津波
    typhoon:    20 # 台風
    meteo:      15 # 隕石
    hugemeteo:  5  # 巨大隕石
    eruption:   10 # 噴火
    fire:       10 # 火災
    maizo:      10 # 埋蔵金
    
    # 地盤沈下
    fall_border: 90 # 安全限界の広さ(hex数)
    falldown:    30 # その広さを超えた場合の確率

    # 怪獣
    monsborder1: 1000 # 人口基準1(怪獣レベル1)
    monsborder2: 2500 # 人口基準2(怪獣レベル2)
    monsborder3: 4000 # 人口基準3(怪獣レベル3)
    monster:     3    # 単位面積あたりの出現率(0.01%単位)

monster:
    # 各基準において出てくる怪獣の番号の最大値
    level1: 2 # サンジラまで    
    level2: 5 # いのらゴーストまで
    level3: 7 # キングいのらまで(全部)

    # 名前
    name: 
    - 'メカいのら'     # 0(人造)
    - 'いのら'         # 1
    - 'サンジラ'       # 2
    - 'レッドいのら'   # 3
    - 'ダークいのら'   # 4
    - 'いのらゴースト' # 5
    - 'クジラ'         # 6
    - 'キングいのら'   # 7

    # 最低体力
    bhp:
      - 2
      - 1
      - 1
      - 3
      - 2
      - 1
      - 4
      - 5
    # 体力の幅
    dhp:
      - 0
      - 2
      - 2
      - 2
      - 2
      - 0
      - 2
      - 2
    # 特殊能力
    special:
      - 0
      - 0
      - 3
      - 0
      - 1
      - 2
      - 4
      - 0
    # 経験値
    exp:
      - 5
      - 5
      - 7
      - 12
      - 15
      - 10
      - 20
      - 30

    # 死体の値段
    value:
      - 0
      - 400
      - 500
      - 1000
      - 800
      - 300
      - 1500
      - 2000

    # 特殊能力の内容は、
    # 0 特になし
    # 1 足が速い(最大2歩あるく)
    # 2 足がとても速い(最大何歩あるくか不明)
    # 3 奇数ターンは硬化
    # 4 偶数ターンは硬化

    # 画像ファイル
    image:
      - 'monster7.gif'
      - 'monster0.gif'
      - 'monster5.gif'
      - 'monster1.gif'
      - 'monster2.gif'
      - 'monster8.gif'
      - 'monster6.gif'
      - 'monster3.gif'

    # 画像ファイルその2(硬化中)
    image2:
      - ''
      - ''
      - 'monster4.gif'
      - ''
      - ''
      - ''
      - 'monster4.gif'
      - ''

# コマンド
command:
  list:
    # 計画番号の設定
    # 整地系
    prepare:      '01' # 整地
    prepare2:     '02' # 地ならし
    reclaim:      '03' # 埋め立て
    destroy:      '04' # 掘削
    selltree:     '05' # 伐採
    
    # 作る系
    plant:        '11' # 植林
    farm:         '12' # 農場整備
    factory:      '13' # 工場建設
    mountain:     '14' # 採掘場整備
    base:         '15' # ミサイル基地建設
    dbase:        '16' # 防衛施設建設
    sbase:        '17' # 海底基地建設
    monument:     '18' # 記念碑建造
    haribote:     '19' # ハリボテ設置
    
    # 発射系
    missilenm:    '31' # ミサイル発射
    missilepp:    '32' # ppミサイル発射
    missilest:    '33' # stミサイル発射
    missileld:    '34' # 陸地破壊弾発射
    sendmonster:  '35' # 怪獣派遣
    
    # 運営系
    donothing:    '41' # 資金繰り
    sell:         '42' # 食料輸出
    money:        '43' # 資金援助
    food:         '44' # 食料援助
    propaganda:   '45' # 誘致活動
    giveup:       '46' # 島の放棄
    
    # 自動入力系
    autoprepare:  '61' # フル整地
    autoprepare2: '62' # フル地ならし
    autodelete:   '63' # 全コマンド消去

  # 計画の名前と値段
  options:
    01:
      name: '整地'
      cost: 5
    
    42:
      name: '食料輸出'
      cost: -100
    
    02:
      name: '地ならし'
      cost: 100
    
    03:
      name: '埋め立て'
      cost: 150
    
    04:
      name: '掘削'
      cost: 200
    
    05:
      name: '伐採'
      cost: 0
    
    11:
      name: '植林'
      cost: 50
    
    12:
      name: '農場整備'
      cost: 20
    
    13:
      name: '工場建設'
      cost: 100
    
    14:
      name: '採掘場整備'
      cost: 300
    
    15:
      name: 'ミサイル基地建設'
      cost: 300
    
    16:
      name: '防衛施設建設'
      cost: 800
    
    17:
      name: '海底基地建設'
      cost: 8000
    
    18:
      name: '記念碑建造'
      cost: 9999
    
    19:
      name: 'ハリボテ設置'
      cost: 1
    
    31:
      name: 'ミサイル発射'
      cost: 20
    
    32:
      name: 'ppミサイル発射'
      cost: 50
    
    33:
      name: 'stミサイル発射'
      cost: 50
    
    34:
      name: '陸地破壊弾発射'
      cost: 100
    
    35:
      name: '怪獣派遣'
      cost: 3000
    
    41:
      name: '資金繰り'
      cost: 0
    
    43:
      name: '資金援助'
      cost: 100
    
    44:
      name: '食料援助'
      cost: -100
    
    45:
      name: '誘致活動'
      cost: 1000
    
    46:
      name: '島の放棄'
      cost: 0
    
    61:
      name: '整地自動入力'
      cost: 0
    
    62:
      name: '地ならし自動入力'
      cost: 0
    
    63:
      name: '全計画を白紙撤回'
      cost: 0